name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-python@v4
        name: Set up Python
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -q

  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: docker/setup-qemu-action@v2
        name: Set up QEMU
      - uses: docker/setup-buildx-action@v2
        name: Set up Buildx
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy_to_local:
    needs: build_and_push
    runs-on: [self-hosted, local-deploy]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: |
          name: CI/CD Pipeline

          on:
            push:
              branches: [main]
            pull_request:
              branches: [main]

          jobs:
            test:
              runs-on: ubuntu-latest
              steps:
                - name: Checkout
                  uses: actions/checkout@v4
                - name: Set up Python
                  uses: actions/setup-python@v4
                  with:
                    python-version: '3.11'
                - name: Install dependencies
                  run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
                - name: Run tests
                  run: pytest -q

            build_and_push:
              needs: test
              runs-on: ubuntu-latest
              permissions:
                contents: read
                packages: write
              steps:
                - name: Checkout
                  uses: actions/checkout@v4
                - name: Set up QEMU
                  uses: docker/setup-qemu-action@v2
                - name: Set up Buildx
                  uses: docker/setup-buildx-action@v2
                - name: Login to GHCR
                  uses: docker/login-action@v2
                  with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
                - name: Build and push image
                  uses: docker/build-push-action@v4
                  with:
                    context: .
                    push: true
                    tags: |
                      ghcr.io/${{ github.repository }}:latest
                      ghcr.io/${{ github.repository }}:${{ github.sha }}

            deploy_to_local:
              needs: build_and_push
              runs-on: [self-hosted, local-deploy]
              if: github.ref == 'refs/heads/main'
              steps:
                - name: Checkout
                  uses: actions/checkout@v4
                - name: Login to GHCR
                  uses: docker/login-action@v2
                  with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
                - name: Pull image
                  run: |
                    IMAGE=ghcr.io/${{ github.repository }}:latest
                    docker pull "$IMAGE"
                - name: Replace container
                  run: |
                    docker stop flask-task-manager || true
                    docker rm -f flask-task-manager || true
                    docker run -d --name flask-task-manager --restart unless-stopped -p 5000:5000 ghcr.io/${{ github.repository }}:latest

            deploy_via_ssh:
              needs: build_and_push
              runs-on: ubuntu-latest
              if: ${{ secrets.SSH_HOST != '' }}
              steps:
                - name: Deploy via SSH
                  uses: appleboy/ssh-action@v0.1.8
                  with:
                    host: ${{ secrets.SSH_HOST }}
                    username: ${{ secrets.SSH_USER }}
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    port: ${{ secrets.SSH_PORT }}
                    script: |
                      set -e
                      IMAGE=ghcr.io/${{ github.repository }}:latest
                      docker pull "$IMAGE" || true
                      docker stop flask-task-manager || true
                      docker rm -f flask-task-manager || true
                      docker run -d --name flask-task-manager --restart unless-stopped -p 5000:5000 "$IMAGE"

